/** Daily source-side RAW export. Existing History Spreadsheet is not required. */
var GSC_RAW_ROOT='热词站监控RAW',GSC_RAW_SOURCE='gsc',GSC_RAW_ROOT_PROPERTY='GSC_MONITORING_RAW_ROOT_FOLDER_ID';
var GSC_RAW_SHEETS=['每日快照','GSC日数据','Query明细','Page明细','Query页面明细','URL索引','决策历史','干预观察','干预时间线'];
function gscDate_(v){var s=v instanceof Date?Utilities.formatDate(v,'Asia/Shanghai','yyyy-MM-dd'):String(v||'').substring(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
function gscRawRootFolder_(create){var p=PropertiesService.getScriptProperties(),f=null,id=p.getProperty(GSC_RAW_ROOT_PROPERTY);if(id)try{f=DriveApp.getFolderById(id);}catch(e){p.deleteProperty(GSC_RAW_ROOT_PROPERTY);}if(!f){var q=DriveApp.getFoldersByName(GSC_RAW_ROOT);if(q.hasNext())f=q.next();}if(!f&&create)f=DriveApp.createFolder(GSC_RAW_ROOT);if(f)p.setProperty(GSC_RAW_ROOT_PROPERTY,f.getId());return f;}
function gscRawDateFolder_(date,create){var f=gscRawRootFolder_(create);if(!f)return null;[GSC_RAW_SOURCE,date.substring(0,4),date.substring(5,7),date].forEach(function(n){var q=f.getFoldersByName(n);f=q.hasNext()?q.next():(create?f.createFolder(n):null);});return f;}
function gscRawSheet_(n){var s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(n);if(!s||s.getLastRow()<1||s.getLastColumn()<1)return null;return{headers:s.getRange(1,1,1,s.getLastColumn()).getValues()[0],rows:s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues():[]};}
function saveGscMonitoringRaw_(runId,date){var d=gscDate_(date)||gscDate_(new Date()),id=String(runId||'').trim()||Utilities.formatDate(new Date(),'Asia/Shanghai','yyyyMMdd-HHmmss'),f=gscRawDateFolder_(d,true),name=id+'.json.gz',q=f.getFilesByName(name);if(q.hasNext())return{saved:false,alreadyExists:true,path:'gsc/'+d+'/'+name};var sheets={};GSC_RAW_SHEETS.forEach(function(n){var t=gscRawSheet_(n);if(t)sheets[n]=t;});var payload={source:'gsc',run_id:id,observed_date:d,exported_at:new Date().toISOString(),sheets:sheets};f.createFile(Utilities.gzip(Utilities.newBlob(JSON.stringify(payload),'application/json',name)));var mf=f.getFilesByName('manifest.json'),m={source:'gsc',date:d,files:[]},file=null;if(mf.hasNext()){file=mf.next();try{m=JSON.parse(file.getBlob().getDataAsString());}catch(e){}}if(!m.files.some(function(x){return x.name===name;})){m.files.push({name:name,run_id:id,sheet_names:Object.keys(sheets)});if(file)file.setContent(JSON.stringify(m,null,2));else f.createFile('manifest.json',JSON.stringify(m,null,2),'application/json');}return{saved:true,path:'gsc/'+d+'/'+name,sheets:Object.keys(sheets)};}
function gscRawDateExists_(date){var d=gscDate_(date),f=d&&gscRawDateFolder_(d,false);if(!f)return false;var files=f.getFiles();while(files.hasNext())if(/\.json\.gz$/.test(files.next().getName()))return true;return false;}
